name: auto-testing
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: sanity-check
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}          

        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install git+https://github.com/iterative/dvc-gdrive
          dvc pull
          dvc repro
